// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-8EOxT_nEOu04WuyUupRezcPrSbHNTx0',
    appId: '1:936087100742:web:77a6d1c2e02b6362259947',
    messagingSenderId: '936087100742',
    projectId: 'first-firebase-62230',
    authDomain: 'first-firebase-62230.firebaseapp.com',
    storageBucket: 'first-firebase-62230.appspot.com',
    measurementId: 'G-9QQT99CMH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_xOfVQ7zHvS-Bj1_fx3OBH91V4XJqMxk',
    appId: '1:936087100742:android:e3b0f223663d4644259947',
    messagingSenderId: '936087100742',
    projectId: 'first-firebase-62230',
    storageBucket: 'first-firebase-62230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkbpIhY49mKHU2ZELwlzyIzl79BC-ed9M',
    appId: '1:936087100742:ios:49962f077501ae2f259947',
    messagingSenderId: '936087100742',
    projectId: 'first-firebase-62230',
    storageBucket: 'first-firebase-62230.appspot.com',
    iosBundleId: 'com.example.firstFirebaseConnection',
  );
}
